
INSERT INTO genre (Nom) VALUES ("Homme");
INSERT INTO genre (Nom) VALUES ("Femme");
INSERT INTO genre (Nom) VALUES ("Non binaire");
INSERT INTO genre (Nom) VALUES ("Autres");

INSERT INTO compte (Nom, Prenom, Date_de_naissance, Code_Gen, Mot_de_passe, Email) VALUES ("Soulier", "Enzo", "2003-06-12", 1, md5("soulier123"), "enzo.soulier@iut-rodez.fr"); 
INSERT INTO compte (Nom, Prenom, Date_de_naissance, Code_Gen, Mot_de_passe, Email) VALUES ("Mars", "Jeanne", "1990-02-05", 2, md5("aurevoir000"), "marsjeanne@gmail.com");
INSERT INTO compte (Nom, Prenom, Date_de_naissance, Code_Gen, Mot_de_passe, Email) VALUES ("Durand", "William", "2020-01-07", null, md5("xxxgamerxxx"), "gamer.william@orange.fr");
INSERT INTO compte (Nom, Prenom, Date_de_naissance, Code_Gen, Mot_de_passe, Email) VALUES ("Dutronc", "Gertrude", null, 2, md5("deuxiemeguerre"), "gertrudelabest@gmail.com");
INSERT INTO compte (Nom, Prenom, Date_de_naissance, Code_Gen, Mot_de_passe, Email) VALUES ("Michel", "Mathis", "2007-06-05", 4, md5("boom123"), "m.michel@gmail.com");
INSERT INTO compte (Nom, Prenom, Date_de_naissance, Code_Gen, Mot_de_passe, Email) VALUES ("Depardieu", "Gérard", "1985-10-10", 1, md5("alcool"), "vinagricole@orange.fr");
INSERT INTO compte (Nom, Prenom, Date_de_naissance, Code_Gen, Mot_de_passe, Email) VALUES ("Chaplin", "Charlie", "1966-04-30", 2, md5("mimedepuis1900"), "mimevie@laposte.net");

INSERT INTO humeur (Libelle, Emoji) VALUES ("Admiration", "🤓");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Adoration", "😃");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Appréciation esthétique", "🤌");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Amusement", "😂");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Anxiété", "🙁");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Colère", "😡");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Calme (sérénité)", "😎");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Confusion", "😕");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Dégoût", "🤮");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Douleur empathique", "💪");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Désir sexuel", "🤤");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Émerveillement", "🤩");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Ennui", "😑");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Envie (craving)", "😋");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Excitation", "😏");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Horreur", "😱");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Intérêt étonné, intrigué", "🧐");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Intérêt", "😯");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Joie", "😁");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Malaise (embarrassement)", "😬");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Nostalgie", "😥");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Peur", "😨");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Romance", "😊");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Soulagement", "😙");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Satisfaction", "😌");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Surprise", "😮");
INSERT INTO humeur (Libelle, Emoji) VALUES ("Tristesse", "😔");

INSERT INTO historique (Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (1, 11, "2022-11-09 08:00:00", "2022-11-09 09:00:00", null);
INSERT INTO historique (Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (6, 9, "2022-11-08 22:30:00", "2022-11-09 09:00:00", "Le vin n'était pas bon !");
INSERT INTO historique (Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (7, 27, "2022-11-09 06:15:00", "2022-11-09 09:05:00", null);
INSERT INTO historique (Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (4, 18, "2022-11-08 23:59:59",  "2022-11-09 09:06:00", "J'ai découvert le nouveau du sport moment");
INSERT INTO historique (Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (3, 22, "2022-11-09 02:50:00", "2022-11-09 08:00:00", "Le film d'horreur m'a terrifié");
INSERT INTO historique (Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (1, 15, "2022-11-09 07:50:00", "2022-11-09 08:30:00", null);
INSERT INTO historique(Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (4, 11, "2022-02-05 12:00:00", "2022-02-05 12:00:00", NULL);
INSERT INTO historique(Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (4, 11, "2022-02-05 12:00:00", "2022-02-05 12:00:00", NULL);
INSERT INTO historique(Code_Compte, Code_hum, Date_Hum, Date_Ajout, Informations) VALUES (4, 1, "2022-02-05 12:00:00", "2022-02-05 12:00:00", NULL);